#!/bin/sh
set -ef
baseurl="$1"
[ -z "$baseurl" ] && { echo >&2 "$0 <base url>"; exit 1; }

histfile=${NFM_HISTFILE="$HOME/.cache/nfm_history"}
previous=$(tail -n1 "$histfile" 2> /dev/null || true)
[ -z "$previous" ] && url="$baseurl" || url=$(dirname "$baseurl$previous")"/"

while true; do
	resp=$(curl -fsg "$url") || {
		echo >&2 'curl get failed, trying again without history'
		url="$baseurl"
		resp=$(curl -fsg "$url") || { echo >&2 'curl get failed again, giving up'; exit 1; }
	}
	lines=$(echo "$resp" | jq -r '.[] | .name + (if .type == "directory" then "/" else "" end)')
	[ -z "$NFM_FILTER" ] || lines=$(echo "$lines" | $NFM_FILTER)
	previdx=$(echo "$lines" | sed 's/ /%20/g' | grep -Fxn "$(basename "$previous")" | cut -d : -f 1)
	if [ "$url" != "$baseurl" ]; then
		[ -z "$lines" ] || lines="$lines
"
		lines="..
$lines/"
	fi
	sel=$(echo "$lines" | $NFM_MENU "$previdx")
	if [ "$sel" = ".." ]; then
		url=$(dirname "$url" | sed 's/ /%20/g')"/"
	elif [ "$sel" = "/" ]; then
		url="$baseurl"
	else
		url="$url$(echo "$sel" | sed 's/ /%20/g')"
		if [ "$(echo "$sel" | tail -c2)" != "/" ]; then
			echo "${url##"$baseurl"}" >> "$histfile"
			$NFM_OPENER "$url"
			exit
		fi
	fi
done
